### ISSUE TITLE
Is the training performed for L2A or L1C?

### ISSUE THREAD

**Issue by EmanuelCastanho** [deephdc/satsr#2]
In "Perform super-resolution" it is referred that "Here is an example of such an url for the Sentinel-2 L2A that you can use for testing purposes".

However, in the "models" folder the "train.txt" of Sentinel-2 only uses files of Level-1C. 

Were the models created with S2 level 1 files or level 2 files?

**Comment by IgnacioHeredia** [comment]
I has been trained  with L1C but does work reasonably well with level L2A if I remember correctly.
